/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables;


import jooq_gen.Keys;
import jooq_gen.Public;
import jooq_gen.tables.records.BestellungsrezeptRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bestellungsrezept extends TableImpl<BestellungsrezeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bestellungsrezept</code>
     */
    public static final Bestellungsrezept BESTELLUNGSREZEPT = new Bestellungsrezept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BestellungsrezeptRecord> getRecordType() {
        return BestellungsrezeptRecord.class;
    }

    /**
     * The column <code>public.bestellungsrezept.bestellnr</code>.
     */
    public final TableField<BestellungsrezeptRecord, Integer> BESTELLNR = createField(DSL.name("bestellnr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.bestellungsrezept.rezeptnr</code>.
     */
    public final TableField<BestellungsrezeptRecord, Integer> REZEPTNR = createField(DSL.name("rezeptnr"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.bestellungsrezept.menge</code>.
     */
    public final TableField<BestellungsrezeptRecord, Integer> MENGE = createField(DSL.name("menge"), SQLDataType.INTEGER, this, "");

    private Bestellungsrezept(Name alias, Table<BestellungsrezeptRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bestellungsrezept(Name alias, Table<BestellungsrezeptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.bestellungsrezept</code> table reference
     */
    public Bestellungsrezept(String alias) {
        this(DSL.name(alias), BESTELLUNGSREZEPT);
    }

    /**
     * Create an aliased <code>public.bestellungsrezept</code> table reference
     */
    public Bestellungsrezept(Name alias) {
        this(alias, BESTELLUNGSREZEPT);
    }

    /**
     * Create a <code>public.bestellungsrezept</code> table reference
     */
    public Bestellungsrezept() {
        this(DSL.name("bestellungsrezept"), null);
    }

    public <O extends Record> Bestellungsrezept(Table<O> child, ForeignKey<O, BestellungsrezeptRecord> key) {
        super(child, key, BESTELLUNGSREZEPT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<BestellungsrezeptRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BESTELLUNGSREZEPT__BESTELLUNGSREZEPT_BESTELLNR_FKEY, Keys.BESTELLUNGSREZEPT__BESTELLUNGSREZEPT_REZEPTNR_FKEY);
    }

    private transient Bestellung _bestellung;
    private transient Rezept _rezept;

    /**
     * Get the implicit join path to the <code>public.bestellung</code> table.
     */
    public Bestellung bestellung() {
        if (_bestellung == null)
            _bestellung = new Bestellung(this, Keys.BESTELLUNGSREZEPT__BESTELLUNGSREZEPT_BESTELLNR_FKEY);

        return _bestellung;
    }

    /**
     * Get the implicit join path to the <code>public.rezept</code> table.
     */
    public Rezept rezept() {
        if (_rezept == null)
            _rezept = new Rezept(this, Keys.BESTELLUNGSREZEPT__BESTELLUNGSREZEPT_REZEPTNR_FKEY);

        return _rezept;
    }

    @Override
    public Bestellungsrezept as(String alias) {
        return new Bestellungsrezept(DSL.name(alias), this);
    }

    @Override
    public Bestellungsrezept as(Name alias) {
        return new Bestellungsrezept(alias, this);
    }

    @Override
    public Bestellungsrezept as(Table<?> alias) {
        return new Bestellungsrezept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungsrezept rename(String name) {
        return new Bestellungsrezept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungsrezept rename(Name name) {
        return new Bestellungsrezept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungsrezept rename(Table<?> name) {
        return new Bestellungsrezept(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
