/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables;


import jooq_gen.Keys;
import jooq_gen.Public;
import jooq_gen.tables.records.BestellungskundeRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bestellungskunde extends TableImpl<BestellungskundeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bestellungskunde</code>
     */
    public static final Bestellungskunde BESTELLUNGSKUNDE = new Bestellungskunde();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BestellungskundeRecord> getRecordType() {
        return BestellungskundeRecord.class;
    }

    /**
     * The column <code>public.bestellungskunde.kundennr</code>.
     */
    public final TableField<BestellungskundeRecord, Integer> KUNDENNR = createField(DSL.name("kundennr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.bestellungskunde.bestellnr</code>.
     */
    public final TableField<BestellungskundeRecord, Integer> BESTELLNR = createField(DSL.name("bestellnr"), SQLDataType.INTEGER.nullable(false), this, "");

    private Bestellungskunde(Name alias, Table<BestellungskundeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bestellungskunde(Name alias, Table<BestellungskundeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.bestellungskunde</code> table reference
     */
    public Bestellungskunde(String alias) {
        this(DSL.name(alias), BESTELLUNGSKUNDE);
    }

    /**
     * Create an aliased <code>public.bestellungskunde</code> table reference
     */
    public Bestellungskunde(Name alias) {
        this(alias, BESTELLUNGSKUNDE);
    }

    /**
     * Create a <code>public.bestellungskunde</code> table reference
     */
    public Bestellungskunde() {
        this(DSL.name("bestellungskunde"), null);
    }

    public <O extends Record> Bestellungskunde(Table<O> child, ForeignKey<O, BestellungskundeRecord> key) {
        super(child, key, BESTELLUNGSKUNDE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<BestellungskundeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BESTELLUNGSKUNDE__BESTELLUNGSKUNDE_KUNDENNR_FKEY, Keys.BESTELLUNGSKUNDE__BESTELLUNGSKUNDE_BESTELLNR_FKEY);
    }

    private transient Kunde _kunde;
    private transient Bestellung _bestellung;

    /**
     * Get the implicit join path to the <code>public.kunde</code> table.
     */
    public Kunde kunde() {
        if (_kunde == null)
            _kunde = new Kunde(this, Keys.BESTELLUNGSKUNDE__BESTELLUNGSKUNDE_KUNDENNR_FKEY);

        return _kunde;
    }

    /**
     * Get the implicit join path to the <code>public.bestellung</code> table.
     */
    public Bestellung bestellung() {
        if (_bestellung == null)
            _bestellung = new Bestellung(this, Keys.BESTELLUNGSKUNDE__BESTELLUNGSKUNDE_BESTELLNR_FKEY);

        return _bestellung;
    }

    @Override
    public Bestellungskunde as(String alias) {
        return new Bestellungskunde(DSL.name(alias), this);
    }

    @Override
    public Bestellungskunde as(Name alias) {
        return new Bestellungskunde(alias, this);
    }

    @Override
    public Bestellungskunde as(Table<?> alias) {
        return new Bestellungskunde(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungskunde rename(String name) {
        return new Bestellungskunde(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungskunde rename(Name name) {
        return new Bestellungskunde(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bestellungskunde rename(Table<?> name) {
        return new Bestellungskunde(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
