/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables;


import jooq_gen.Keys;
import jooq_gen.Public;
import jooq_gen.tables.records.RezeptRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rezept extends TableImpl<RezeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.rezept</code>
     */
    public static final Rezept REZEPT = new Rezept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RezeptRecord> getRecordType() {
        return RezeptRecord.class;
    }

    /**
     * The column <code>public.rezept.rezeptnr</code>.
     */
    public final TableField<RezeptRecord, Integer> REZEPTNR = createField(DSL.name("rezeptnr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.rezept.rezeptname</code>.
     */
    public final TableField<RezeptRecord, String> REZEPTNAME = createField(DSL.name("rezeptname"), SQLDataType.VARCHAR(50), this, "");

    private Rezept(Name alias, Table<RezeptRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rezept(Name alias, Table<RezeptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.rezept</code> table reference
     */
    public Rezept(String alias) {
        this(DSL.name(alias), REZEPT);
    }

    /**
     * Create an aliased <code>public.rezept</code> table reference
     */
    public Rezept(Name alias) {
        this(alias, REZEPT);
    }

    /**
     * Create a <code>public.rezept</code> table reference
     */
    public Rezept() {
        this(DSL.name("rezept"), null);
    }

    public <O extends Record> Rezept(Table<O> child, ForeignKey<O, RezeptRecord> key) {
        super(child, key, REZEPT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RezeptRecord> getPrimaryKey() {
        return Keys.REZEPT_PKEY;
    }

    @Override
    public Rezept as(String alias) {
        return new Rezept(DSL.name(alias), this);
    }

    @Override
    public Rezept as(Name alias) {
        return new Rezept(alias, this);
    }

    @Override
    public Rezept as(Table<?> alias) {
        return new Rezept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rezept rename(String name) {
        return new Rezept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rezept rename(Name name) {
        return new Rezept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rezept rename(Table<?> name) {
        return new Rezept(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
