/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Beschraenkungen;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BeschraenkungenRecord extends UpdatableRecordImpl<BeschraenkungenRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.beschraenkungen.beschraenkungid</code>.
     */
    public BeschraenkungenRecord setBeschraenkungid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.beschraenkungen.beschraenkungid</code>.
     */
    public Integer getBeschraenkungid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.beschraenkungen.beschreibung</code>.
     */
    public BeschraenkungenRecord setBeschreibung(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.beschraenkungen.beschreibung</code>.
     */
    public String getBeschreibung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Beschraenkungen.BESCHRAENKUNGEN.BESCHRAENKUNGID;
    }

    @Override
    public Field<String> field2() {
        return Beschraenkungen.BESCHRAENKUNGEN.BESCHREIBUNG;
    }

    @Override
    public Integer component1() {
        return getBeschraenkungid();
    }

    @Override
    public String component2() {
        return getBeschreibung();
    }

    @Override
    public Integer value1() {
        return getBeschraenkungid();
    }

    @Override
    public String value2() {
        return getBeschreibung();
    }

    @Override
    public BeschraenkungenRecord value1(Integer value) {
        setBeschraenkungid(value);
        return this;
    }

    @Override
    public BeschraenkungenRecord value2(String value) {
        setBeschreibung(value);
        return this;
    }

    @Override
    public BeschraenkungenRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BeschraenkungenRecord
     */
    public BeschraenkungenRecord() {
        super(Beschraenkungen.BESCHRAENKUNGEN);
    }

    /**
     * Create a detached, initialised BeschraenkungenRecord
     */
    public BeschraenkungenRecord(Integer beschraenkungid, String beschreibung) {
        super(Beschraenkungen.BESCHRAENKUNGEN);

        setBeschraenkungid(beschraenkungid);
        setBeschreibung(beschreibung);
    }
}
