/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Bestellungsrezept;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BestellungsrezeptRecord extends TableRecordImpl<BestellungsrezeptRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bestellungsrezept.bestellnr</code>.
     */
    public BestellungsrezeptRecord setBestellnr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungsrezept.bestellnr</code>.
     */
    public Integer getBestellnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bestellungsrezept.rezeptnr</code>.
     */
    public BestellungsrezeptRecord setRezeptnr(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungsrezept.rezeptnr</code>.
     */
    public Integer getRezeptnr() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.bestellungsrezept.menge</code>.
     */
    public BestellungsrezeptRecord setMenge(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungsrezept.menge</code>.
     */
    public Integer getMenge() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Bestellungsrezept.BESTELLUNGSREZEPT.BESTELLNR;
    }

    @Override
    public Field<Integer> field2() {
        return Bestellungsrezept.BESTELLUNGSREZEPT.REZEPTNR;
    }

    @Override
    public Field<Integer> field3() {
        return Bestellungsrezept.BESTELLUNGSREZEPT.MENGE;
    }

    @Override
    public Integer component1() {
        return getBestellnr();
    }

    @Override
    public Integer component2() {
        return getRezeptnr();
    }

    @Override
    public Integer component3() {
        return getMenge();
    }

    @Override
    public Integer value1() {
        return getBestellnr();
    }

    @Override
    public Integer value2() {
        return getRezeptnr();
    }

    @Override
    public Integer value3() {
        return getMenge();
    }

    @Override
    public BestellungsrezeptRecord value1(Integer value) {
        setBestellnr(value);
        return this;
    }

    @Override
    public BestellungsrezeptRecord value2(Integer value) {
        setRezeptnr(value);
        return this;
    }

    @Override
    public BestellungsrezeptRecord value3(Integer value) {
        setMenge(value);
        return this;
    }

    @Override
    public BestellungsrezeptRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BestellungsrezeptRecord
     */
    public BestellungsrezeptRecord() {
        super(Bestellungsrezept.BESTELLUNGSREZEPT);
    }

    /**
     * Create a detached, initialised BestellungsrezeptRecord
     */
    public BestellungsrezeptRecord(Integer bestellnr, Integer rezeptnr, Integer menge) {
        super(Bestellungsrezept.BESTELLUNGSREZEPT);

        setBestellnr(bestellnr);
        setRezeptnr(rezeptnr);
        setMenge(menge);
    }
}
