/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Bestellungzutat;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BestellungzutatRecord extends TableRecordImpl<BestellungzutatRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bestellungzutat.bestellnr</code>.
     */
    public BestellungzutatRecord setBestellnr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungzutat.bestellnr</code>.
     */
    public Integer getBestellnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bestellungzutat.zutatnr</code>.
     */
    public BestellungzutatRecord setZutatnr(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungzutat.zutatnr</code>.
     */
    public Integer getZutatnr() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.bestellungzutat.menge</code>.
     */
    public BestellungzutatRecord setMenge(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bestellungzutat.menge</code>.
     */
    public Integer getMenge() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Bestellungzutat.BESTELLUNGZUTAT.BESTELLNR;
    }

    @Override
    public Field<Integer> field2() {
        return Bestellungzutat.BESTELLUNGZUTAT.ZUTATNR;
    }

    @Override
    public Field<Integer> field3() {
        return Bestellungzutat.BESTELLUNGZUTAT.MENGE;
    }

    @Override
    public Integer component1() {
        return getBestellnr();
    }

    @Override
    public Integer component2() {
        return getZutatnr();
    }

    @Override
    public Integer component3() {
        return getMenge();
    }

    @Override
    public Integer value1() {
        return getBestellnr();
    }

    @Override
    public Integer value2() {
        return getZutatnr();
    }

    @Override
    public Integer value3() {
        return getMenge();
    }

    @Override
    public BestellungzutatRecord value1(Integer value) {
        setBestellnr(value);
        return this;
    }

    @Override
    public BestellungzutatRecord value2(Integer value) {
        setZutatnr(value);
        return this;
    }

    @Override
    public BestellungzutatRecord value3(Integer value) {
        setMenge(value);
        return this;
    }

    @Override
    public BestellungzutatRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BestellungzutatRecord
     */
    public BestellungzutatRecord() {
        super(Bestellungzutat.BESTELLUNGZUTAT);
    }

    /**
     * Create a detached, initialised BestellungzutatRecord
     */
    public BestellungzutatRecord(Integer bestellnr, Integer zutatnr, Integer menge) {
        super(Bestellungzutat.BESTELLUNGZUTAT);

        setBestellnr(bestellnr);
        setZutatnr(zutatnr);
        setMenge(menge);
    }
}
