/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Eigenschaften;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EigenschaftenRecord extends UpdatableRecordImpl<EigenschaftenRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eigenschaften.eigenschaftid</code>.
     */
    public EigenschaftenRecord setEigenschaftid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.eigenschaften.eigenschaftid</code>.
     */
    public Integer getEigenschaftid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.eigenschaften.bezeichnung</code>.
     */
    public EigenschaftenRecord setBezeichnung(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.eigenschaften.bezeichnung</code>.
     */
    public String getBezeichnung() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Eigenschaften.EIGENSCHAFTEN.EIGENSCHAFTID;
    }

    @Override
    public Field<String> field2() {
        return Eigenschaften.EIGENSCHAFTEN.BEZEICHNUNG;
    }

    @Override
    public Integer component1() {
        return getEigenschaftid();
    }

    @Override
    public String component2() {
        return getBezeichnung();
    }

    @Override
    public Integer value1() {
        return getEigenschaftid();
    }

    @Override
    public String value2() {
        return getBezeichnung();
    }

    @Override
    public EigenschaftenRecord value1(Integer value) {
        setEigenschaftid(value);
        return this;
    }

    @Override
    public EigenschaftenRecord value2(String value) {
        setBezeichnung(value);
        return this;
    }

    @Override
    public EigenschaftenRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EigenschaftenRecord
     */
    public EigenschaftenRecord() {
        super(Eigenschaften.EIGENSCHAFTEN);
    }

    /**
     * Create a detached, initialised EigenschaftenRecord
     */
    public EigenschaftenRecord(Integer eigenschaftid, String bezeichnung) {
        super(Eigenschaften.EIGENSCHAFTEN);

        setEigenschaftid(eigenschaftid);
        setBezeichnung(bezeichnung);
    }
}
