/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Getrezeptebyzutateigenschaft;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetrezeptebyzutateigenschaftRecord extends TableRecordImpl<GetrezeptebyzutateigenschaftRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.getrezeptebyzutateigenschaft.rezeptnr</code>.
     */
    public GetrezeptebyzutateigenschaftRecord setRezeptnr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.getrezeptebyzutateigenschaft.rezeptnr</code>.
     */
    public Integer getRezeptnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.getrezeptebyzutateigenschaft.rezeptname</code>.
     */
    public GetrezeptebyzutateigenschaftRecord setRezeptname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.getrezeptebyzutateigenschaft.rezeptname</code>.
     */
    public String getRezeptname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.REZEPTNR;
    }

    @Override
    public Field<String> field2() {
        return Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.REZEPTNAME;
    }

    @Override
    public Integer component1() {
        return getRezeptnr();
    }

    @Override
    public String component2() {
        return getRezeptname();
    }

    @Override
    public Integer value1() {
        return getRezeptnr();
    }

    @Override
    public String value2() {
        return getRezeptname();
    }

    @Override
    public GetrezeptebyzutateigenschaftRecord value1(Integer value) {
        setRezeptnr(value);
        return this;
    }

    @Override
    public GetrezeptebyzutateigenschaftRecord value2(String value) {
        setRezeptname(value);
        return this;
    }

    @Override
    public GetrezeptebyzutateigenschaftRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetrezeptebyzutateigenschaftRecord
     */
    public GetrezeptebyzutateigenschaftRecord() {
        super(Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT);
    }

    /**
     * Create a detached, initialised GetrezeptebyzutateigenschaftRecord
     */
    public GetrezeptebyzutateigenschaftRecord(Integer rezeptnr, String rezeptname) {
        super(Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT);

        setRezeptnr(rezeptnr);
        setRezeptname(rezeptname);
    }
}
