/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Kunde;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KundeRecord extends UpdatableRecordImpl<KundeRecord> implements Record7<Integer, String, String, LocalDate, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.kunde.kundennr</code>.
     */
    public KundeRecord setKundennr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.kundennr</code>.
     */
    public Integer getKundennr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.kunde.nachname</code>.
     */
    public KundeRecord setNachname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.nachname</code>.
     */
    public String getNachname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kunde.vorname</code>.
     */
    public KundeRecord setVorname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.vorname</code>.
     */
    public String getVorname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.kunde.geburtsdatum</code>.
     */
    public KundeRecord setGeburtsdatum(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.geburtsdatum</code>.
     */
    public LocalDate getGeburtsdatum() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.kunde.telefon</code>.
     */
    public KundeRecord setTelefon(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.telefon</code>.
     */
    public String getTelefon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.kunde.email</code>.
     */
    public KundeRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.kunde.adressid</code>.
     */
    public KundeRecord setAdressid(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.kunde.adressid</code>.
     */
    public Integer getAdressid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, LocalDate, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, LocalDate, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Kunde.KUNDE.KUNDENNR;
    }

    @Override
    public Field<String> field2() {
        return Kunde.KUNDE.NACHNAME;
    }

    @Override
    public Field<String> field3() {
        return Kunde.KUNDE.VORNAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Kunde.KUNDE.GEBURTSDATUM;
    }

    @Override
    public Field<String> field5() {
        return Kunde.KUNDE.TELEFON;
    }

    @Override
    public Field<String> field6() {
        return Kunde.KUNDE.EMAIL;
    }

    @Override
    public Field<Integer> field7() {
        return Kunde.KUNDE.ADRESSID;
    }

    @Override
    public Integer component1() {
        return getKundennr();
    }

    @Override
    public String component2() {
        return getNachname();
    }

    @Override
    public String component3() {
        return getVorname();
    }

    @Override
    public LocalDate component4() {
        return getGeburtsdatum();
    }

    @Override
    public String component5() {
        return getTelefon();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public Integer component7() {
        return getAdressid();
    }

    @Override
    public Integer value1() {
        return getKundennr();
    }

    @Override
    public String value2() {
        return getNachname();
    }

    @Override
    public String value3() {
        return getVorname();
    }

    @Override
    public LocalDate value4() {
        return getGeburtsdatum();
    }

    @Override
    public String value5() {
        return getTelefon();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public Integer value7() {
        return getAdressid();
    }

    @Override
    public KundeRecord value1(Integer value) {
        setKundennr(value);
        return this;
    }

    @Override
    public KundeRecord value2(String value) {
        setNachname(value);
        return this;
    }

    @Override
    public KundeRecord value3(String value) {
        setVorname(value);
        return this;
    }

    @Override
    public KundeRecord value4(LocalDate value) {
        setGeburtsdatum(value);
        return this;
    }

    @Override
    public KundeRecord value5(String value) {
        setTelefon(value);
        return this;
    }

    @Override
    public KundeRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public KundeRecord value7(Integer value) {
        setAdressid(value);
        return this;
    }

    @Override
    public KundeRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KundeRecord
     */
    public KundeRecord() {
        super(Kunde.KUNDE);
    }

    /**
     * Create a detached, initialised KundeRecord
     */
    public KundeRecord(Integer kundennr, String nachname, String vorname, LocalDate geburtsdatum, String telefon, String email, Integer adressid) {
        super(Kunde.KUNDE);

        setKundennr(kundennr);
        setNachname(nachname);
        setVorname(vorname);
        setGeburtsdatum(geburtsdatum);
        setTelefon(telefon);
        setEmail(email);
        setAdressid(adressid);
    }
}
