/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Lieferant;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LieferantRecord extends UpdatableRecordImpl<LieferantRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lieferant.lieferantennr</code>.
     */
    public LieferantRecord setLieferantennr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.lieferant.lieferantennr</code>.
     */
    public Integer getLieferantennr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lieferant.lieferantenname</code>.
     */
    public LieferantRecord setLieferantenname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.lieferant.lieferantenname</code>.
     */
    public String getLieferantenname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lieferant.telefon</code>.
     */
    public LieferantRecord setTelefon(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.lieferant.telefon</code>.
     */
    public String getTelefon() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lieferant.email</code>.
     */
    public LieferantRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.lieferant.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.lieferant.adressid</code>.
     */
    public LieferantRecord setAdressid(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.lieferant.adressid</code>.
     */
    public Integer getAdressid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Lieferant.LIEFERANT.LIEFERANTENNR;
    }

    @Override
    public Field<String> field2() {
        return Lieferant.LIEFERANT.LIEFERANTENNAME;
    }

    @Override
    public Field<String> field3() {
        return Lieferant.LIEFERANT.TELEFON;
    }

    @Override
    public Field<String> field4() {
        return Lieferant.LIEFERANT.EMAIL;
    }

    @Override
    public Field<Integer> field5() {
        return Lieferant.LIEFERANT.ADRESSID;
    }

    @Override
    public Integer component1() {
        return getLieferantennr();
    }

    @Override
    public String component2() {
        return getLieferantenname();
    }

    @Override
    public String component3() {
        return getTelefon();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public Integer component5() {
        return getAdressid();
    }

    @Override
    public Integer value1() {
        return getLieferantennr();
    }

    @Override
    public String value2() {
        return getLieferantenname();
    }

    @Override
    public String value3() {
        return getTelefon();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public Integer value5() {
        return getAdressid();
    }

    @Override
    public LieferantRecord value1(Integer value) {
        setLieferantennr(value);
        return this;
    }

    @Override
    public LieferantRecord value2(String value) {
        setLieferantenname(value);
        return this;
    }

    @Override
    public LieferantRecord value3(String value) {
        setTelefon(value);
        return this;
    }

    @Override
    public LieferantRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public LieferantRecord value5(Integer value) {
        setAdressid(value);
        return this;
    }

    @Override
    public LieferantRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LieferantRecord
     */
    public LieferantRecord() {
        super(Lieferant.LIEFERANT);
    }

    /**
     * Create a detached, initialised LieferantRecord
     */
    public LieferantRecord(Integer lieferantennr, String lieferantenname, String telefon, String email, Integer adressid) {
        super(Lieferant.LIEFERANT);

        setLieferantennr(lieferantennr);
        setLieferantenname(lieferantenname);
        setTelefon(telefon);
        setEmail(email);
        setAdressid(adressid);
    }
}
