/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Rezept;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RezeptRecord extends UpdatableRecordImpl<RezeptRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rezept.rezeptnr</code>.
     */
    public RezeptRecord setRezeptnr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.rezept.rezeptnr</code>.
     */
    public Integer getRezeptnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.rezept.rezeptname</code>.
     */
    public RezeptRecord setRezeptname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.rezept.rezeptname</code>.
     */
    public String getRezeptname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Rezept.REZEPT.REZEPTNR;
    }

    @Override
    public Field<String> field2() {
        return Rezept.REZEPT.REZEPTNAME;
    }

    @Override
    public Integer component1() {
        return getRezeptnr();
    }

    @Override
    public String component2() {
        return getRezeptname();
    }

    @Override
    public Integer value1() {
        return getRezeptnr();
    }

    @Override
    public String value2() {
        return getRezeptname();
    }

    @Override
    public RezeptRecord value1(Integer value) {
        setRezeptnr(value);
        return this;
    }

    @Override
    public RezeptRecord value2(String value) {
        setRezeptname(value);
        return this;
    }

    @Override
    public RezeptRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RezeptRecord
     */
    public RezeptRecord() {
        super(Rezept.REZEPT);
    }

    /**
     * Create a detached, initialised RezeptRecord
     */
    public RezeptRecord(Integer rezeptnr, String rezeptname) {
        super(Rezept.REZEPT);

        setRezeptnr(rezeptnr);
        setRezeptname(rezeptname);
    }
}
