/*
 * This file is generated by jOOQ.
 */
package jooq_gen.tables.records;


import jooq_gen.tables.Zutatbeschraenkung;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZutatbeschraenkungRecord extends TableRecordImpl<ZutatbeschraenkungRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.zutatbeschraenkung.zutatnr</code>.
     */
    public ZutatbeschraenkungRecord setZutatnr(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.zutatbeschraenkung.zutatnr</code>.
     */
    public Integer getZutatnr() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.zutatbeschraenkung.beschraenkungid</code>.
     */
    public ZutatbeschraenkungRecord setBeschraenkungid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.zutatbeschraenkung.beschraenkungid</code>.
     */
    public Integer getBeschraenkungid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Zutatbeschraenkung.ZUTATBESCHRAENKUNG.ZUTATNR;
    }

    @Override
    public Field<Integer> field2() {
        return Zutatbeschraenkung.ZUTATBESCHRAENKUNG.BESCHRAENKUNGID;
    }

    @Override
    public Integer component1() {
        return getZutatnr();
    }

    @Override
    public Integer component2() {
        return getBeschraenkungid();
    }

    @Override
    public Integer value1() {
        return getZutatnr();
    }

    @Override
    public Integer value2() {
        return getBeschraenkungid();
    }

    @Override
    public ZutatbeschraenkungRecord value1(Integer value) {
        setZutatnr(value);
        return this;
    }

    @Override
    public ZutatbeschraenkungRecord value2(Integer value) {
        setBeschraenkungid(value);
        return this;
    }

    @Override
    public ZutatbeschraenkungRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZutatbeschraenkungRecord
     */
    public ZutatbeschraenkungRecord() {
        super(Zutatbeschraenkung.ZUTATBESCHRAENKUNG);
    }

    /**
     * Create a detached, initialised ZutatbeschraenkungRecord
     */
    public ZutatbeschraenkungRecord(Integer zutatnr, Integer beschraenkungid) {
        super(Zutatbeschraenkung.ZUTATBESCHRAENKUNG);

        setZutatnr(zutatnr);
        setBeschraenkungid(beschraenkungid);
    }
}
