/*
 * This file is generated by jOOQ.
 */
package jooq_gen;


import jooq_gen.tables.*;
import jooq_gen.tables.records.GetrezeptebyzutateigenschaftRecord;
import org.jooq.*;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.adresse</code>.
     */
    public final Adresse ADRESSE = Adresse.ADRESSE;

    /**
     * The table <code>public.beschraenkungen</code>.
     */
    public final Beschraenkungen BESCHRAENKUNGEN = Beschraenkungen.BESCHRAENKUNGEN;

    /**
     * The table <code>public.bestellung</code>.
     */
    public final Bestellung BESTELLUNG = Bestellung.BESTELLUNG;

    /**
     * The table <code>public.bestellungskunde</code>.
     */
    public final Bestellungskunde BESTELLUNGSKUNDE = Bestellungskunde.BESTELLUNGSKUNDE;

    /**
     * The table <code>public.bestellungsrezept</code>.
     */
    public final Bestellungsrezept BESTELLUNGSREZEPT = Bestellungsrezept.BESTELLUNGSREZEPT;

    /**
     * The table <code>public.bestellungzutat</code>.
     */
    public final Bestellungzutat BESTELLUNGZUTAT = Bestellungzutat.BESTELLUNGZUTAT;

    /**
     * The table <code>public.eigenschaften</code>.
     */
    public final Eigenschaften EIGENSCHAFTEN = Eigenschaften.EIGENSCHAFTEN;

    /**
     * The table <code>public.getrezeptebyzutateigenschaft</code>.
     */
    public final Getrezeptebyzutateigenschaft GETREZEPTEBYZUTATEIGENSCHAFT = Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT;

    /**
     * Call <code>public.getrezeptebyzutateigenschaft</code>.
     */
    public static Result<GetrezeptebyzutateigenschaftRecord> GETREZEPTEBYZUTATEIGENSCHAFT(
          Configuration configuration
        , String eigenschaftname
    ) {
        return configuration.dsl().selectFrom(jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
              eigenschaftname
        )).fetch();
    }

    /**
     * Get <code>public.getrezeptebyzutateigenschaft</code> as a table.
     */
    public static Getrezeptebyzutateigenschaft GETREZEPTEBYZUTATEIGENSCHAFT(
          String eigenschaftname
    ) {
        return jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
            eigenschaftname
        );
    }

    /**
     * Get <code>public.getrezeptebyzutateigenschaft</code> as a table.
     */
    public static Getrezeptebyzutateigenschaft GETREZEPTEBYZUTATEIGENSCHAFT(
          Field<String> eigenschaftname
    ) {
        return jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
            eigenschaftname
        );
    }

    /**
     * The table <code>public.kunde</code>.
     */
    public final Kunde KUNDE = Kunde.KUNDE;

    /**
     * The table <code>public.lieferant</code>.
     */
    public final Lieferant LIEFERANT = Lieferant.LIEFERANT;

    /**
     * The table <code>public.region</code>.
     */
    public final Region REGION = Region.REGION;

    /**
     * The table <code>public.rezept</code>.
     */
    public final Rezept REZEPT = Rezept.REZEPT;

    /**
     * The table <code>public.rezeptzutat</code>.
     */
    public final Rezeptzutat REZEPTZUTAT = Rezeptzutat.REZEPTZUTAT;

    /**
     * The table <code>public.zutat</code>.
     */
    public final Zutat ZUTAT = Zutat.ZUTAT;

    /**
     * The table <code>public.zutatbeschraenkung</code>.
     */
    public final Zutatbeschraenkung ZUTATBESCHRAENKUNG = Zutatbeschraenkung.ZUTATBESCHRAENKUNG;

    /**
     * The table <code>public.zutateigenschaft</code>.
     */
    public final Zutateigenschaft ZUTATEIGENSCHAFT = Zutateigenschaft.ZUTATEIGENSCHAFT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Adresse.ADRESSE,
            Beschraenkungen.BESCHRAENKUNGEN,
            Bestellung.BESTELLUNG,
            Bestellungskunde.BESTELLUNGSKUNDE,
            Bestellungsrezept.BESTELLUNGSREZEPT,
            Bestellungzutat.BESTELLUNGZUTAT,
            Eigenschaften.EIGENSCHAFTEN,
            Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT,
            Kunde.KUNDE,
            Lieferant.LIEFERANT,
            Region.REGION,
            Rezept.REZEPT,
            Rezeptzutat.REZEPTZUTAT,
            Zutat.ZUTAT,
            Zutatbeschraenkung.ZUTATBESCHRAENKUNG,
            Zutateigenschaft.ZUTATEIGENSCHAFT
        );
    }
}
