/*
 * This file is generated by jOOQ.
 */
package jooq_gen;


import jooq_gen.tables.Getrezeptebyzutateigenschaft;
import jooq_gen.tables.records.GetrezeptebyzutateigenschaftRecord;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.getrezeptebyzutateigenschaft</code>.
     */
    public static Result<GetrezeptebyzutateigenschaftRecord> getrezeptebyzutateigenschaft(
          Configuration configuration
        , String eigenschaftname
    ) {
        return configuration.dsl().selectFrom(jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
              eigenschaftname
        )).fetch();
    }

    /**
     * Get <code>public.getrezeptebyzutateigenschaft</code> as a table.
     */
    public static Getrezeptebyzutateigenschaft getrezeptebyzutateigenschaft(
          String eigenschaftname
    ) {
        return jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
            eigenschaftname
        );
    }

    /**
     * Get <code>public.getrezeptebyzutateigenschaft</code> as a table.
     */
    public static Getrezeptebyzutateigenschaft getrezeptebyzutateigenschaft(
          Field<String> eigenschaftname
    ) {
        return jooq_gen.tables.Getrezeptebyzutateigenschaft.GETREZEPTEBYZUTATEIGENSCHAFT.call(
            eigenschaftname
        );
    }
}
